//
//  ExportView.swift
//  iMOPS-Gastro-Grid
//
//  Created by Andreas Pelczer on 07.02.26.
//


//
//  ExportView.swift
//  iMOPS-Gastro-Grid
//
//  Phase 1 Audit-Ready: Export Screen mit iMOPS Version + Seal.
//  Bietet Tagesbericht (Text), Audit CSV, Journal JSON.
//  Jeder Export wird versiegelt und als AuditEvent protokolliert.
//

import SwiftUI
import SwiftData

@available(iOS 17.0, *)
struct ExportView: View {
    let auditTrail: AuditTrail?
    let journal: Journal?
    let brain: TheBrain

    @State private var selectedDate = Date()
    @State private var lastExportSeal: String?
    @State private var lastExportFormat: String?
    @State private var isExporting = false
    @State private var showShareSheet = false
    @State private var exportContent: String = ""

    var body: some View {
        List {
            // Version Info
            Section {
                LabeledContent("iMOPS Version") {
                    Text(HACCPExporter.iMOPSVersion)
                        .font(.caption.monospaced())
                }
            } header: {
                Text("System")
            }

            // Date Selection
            Section {
                DatePicker("Datum", selection: $selectedDate, displayedComponents: .date)
            } header: {
                Text("Exportzeitraum")
            }

            // Export Actions
            Section {
                Button {
                    exportDailyReport()
                } label: {
                    Label("Tagesbericht (Text)", systemImage: "doc.text")
                }
                .disabled(isExporting || auditTrail == nil || journal == nil)

                Button {
                    exportCSV()
                } label: {
                    Label("Audit CSV", systemImage: "tablecells")
                }
                .disabled(isExporting || auditTrail == nil)

                Button {
                    exportJSON()
                } label: {
                    Label("Journal JSON", systemImage: "curlybraces")
                }
                .disabled(isExporting || journal == nil)
            } header: {
                Text("Export erstellen")
            } footer: {
                Text("Jeder Export wird mit SHA-256 versiegelt und im Audit-Log protokolliert.")
                    .font(.caption2)
            }

            // Last Export Seal
            if let seal = lastExportSeal {
                Section {
                    LabeledContent("Format") {
                        Text(lastExportFormat ?? "–")
                            .font(.caption)
                    }
                    LabeledContent("Seal") {
                        Text(ExportSeal.shortened(seal))
                            .font(.caption.monospaced())
                    }
                } header: {
                    Text("Letzter Export")
                }
            }

            // Footer Preview
            Section {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Generated by iMOPS v\(HACCPExporter.iMOPSVersionShort)")
                        .font(.caption.monospaced())
                        .foregroundStyle(.secondary)
                    if let seal = lastExportSeal {
                        Text("Seal: \(ExportSeal.shortened(seal))")
                            .font(.caption.monospaced())
                            .foregroundStyle(.secondary)
                    }
                }
            } header: {
                Text("PDF Footer Vorschau")
            }
        }
        .navigationTitle("Export")
        .sheet(isPresented: $showShareSheet) {
            ShareSheet(content: exportContent)
        }
    }

    // MARK: - Export Actions

    private func exportDailyReport() {
        guard let trail = auditTrail, let journal = journal else { return }
        isExporting = true

        DispatchQueue.global(qos: .userInitiated).async {
            let result = HACCPExporter.generateDailyReport(
                date: selectedDate,
                auditTrail: trail,
                journal: journal,
                brain: brain
            )

            DispatchQueue.main.async {
                exportContent = result.content
                lastExportSeal = result.sealHash
                lastExportFormat = "Tagesbericht (Text)"
                isExporting = false
                showShareSheet = true
            }
        }
    }

    private func exportCSV() {
        guard let trail = auditTrail else { return }
        isExporting = true

        DispatchQueue.global(qos: .userInitiated).async {
            let result = HACCPExporter.exportAuditCSV(auditTrail: trail)

            DispatchQueue.main.async {
                exportContent = result.content
                lastExportSeal = result.sealHash
                lastExportFormat = "Audit CSV"
                isExporting = false
                showShareSheet = true
            }
        }
    }

    private func exportJSON() {
        guard let journal = journal else { return }
        isExporting = true

        DispatchQueue.global(qos: .userInitiated).async {
            let result = HACCPExporter.exportJournalJSON(journal: journal, auditTrail: auditTrail)

            DispatchQueue.main.async {
                exportContent = result.content
                lastExportSeal = result.sealHash
                lastExportFormat = "Journal JSON"
                isExporting = false
                showShareSheet = true
            }
        }
    }
}

// MARK: - ShareSheet (UIKit Bridge)

struct ShareSheet: UIViewControllerRepresentable {
    let content: String

    func makeUIViewController(context: Context) -> UIActivityViewController {
        let items: [Any] = [content]
        return UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}